version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=restapi_dev
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
    command: ["postgres"]
    ports:
      - "5432:5432"
